project 'ex00.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ex00' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ex00
  pod 'Firebase/Core', '~> 5'
  pod 'Firebase/Functions'
end
